### ISSUE TITLE
php console App seed error

### ISSUE THREAD

**Issue by lindsaymshepard** [susanBuck/e2-fall19#106]
During project setup for the seed I am getting this error in terminal:

```bash
LindsayShepard@Lindsays-MBP p4 % php console App seed
"Executing App\Commands\AppCommand@seed"
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content' in 'field list' in /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/susanbuck/e2core/src/Database.php:31
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/susanbuck/e2core/src/Database.php(31): PDO->prepare('INSERT INTO his...')
#1 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/susanbuck/e2core/src/Database.php(58): E2\Database->run('INSERT INTO his...', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/app/Commands/AppCommand.php(37): E2\Database->insert('history', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/susanbuck/e2core/src/App.php(80): App\Commands\AppCommand->seed()
#4 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/console(12): E2\App->console(Array)
#5 {main}
  thrown in /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/susanbuck/e2core/src/Database.php on line 31

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content' in 'field list' in /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/susanbuck/e2core/src/Database.php:31
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/susanbuck/e2core/src/Database.php(31): PDO->prepare('INSERT INTO his...')
#1 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/susanbuck/e2core/src/Database.php(58): E2\Database->run('INSERT INTO his...', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/app/Commands/AppCommand.php(37): E2\Database->insert('history', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/susanbuck/e2core/src/App.php(80): App\Commands\AppCommand->seed()
#4 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/console(12): E2\App->console(Array)
#5 {main}
  thrown in /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/susanbuck/e2core/src/Database.php on line 31
```

here is my code for the public functions

```php
class AppCommand extends Command
{
    public function test()
    {
        dump('It works! You invoked your first command.');
    }

    public function migrate()
    {
        $this->app->db()->createTable('history', [
            'title' => 'varchar(255)',
            'history' => 'text',
    ]);
        dump('Migration complete.');

    }

    public function seed()
    {
        # Instantiate a new instance of the Faker\Factory class
$faker = \Faker\Factory::create();

# Use a loop to create 10 history
for ($i = 0; $i < 10; $i++) {

    # Set up a history
    $history = [
        'title' => $faker->sentences(1,true),
        'content' => $faker->sentences(3, true),
    ];

    # Insert the history
    $this->app->db()->insert('history', $history);

    }
}

    public function fresh()
    {

        $this->migrate();
        $this->seed();
    }
}
```

**Comment by susanBuck** [comment]
Hi @lindsaymshepard 

In your migration you create fields called `title` and `history`.

Then in your seed, you insert data into fields called `title` and `content`.

The error notes - `Unknown column 'content'` - you're trying to insert data into a field called `content`, but no such field exists.

p.s./FYI: I edited your post to add markdown formatting to make the error output and code more legible.

**Comment by lindsaymshepard** [comment]
Thank you! That fixed the issue.
