### ISSUE TITLE
Unknown Database name when I invoke migrations

### ISSUE THREAD

**Issue by janenycxo** [susanBuck/e2-fall19#108]
when I enter the command- php console App migrate, I get this error message -

```
c:\xampp\htdocs\e2\p4 (master){hg}
λ php console App migrate
"Executing App\Commands\AppCommand@migrate"
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1049] Unknown database 'my app' in C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\Database.php:22
Stack trace:
#0 C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\App.php(100): E2\Database->__construct('127.0.0.1', 'my app', 'root', NULL, 'utf8mb4')
#1 C:\xampp\htdocs\e2\p4\app\Commands\AppCommand.php(20): E2\App->db()
#2 C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\App.php(80): App\Commands\AppCommand->migrate()
#3 C:\xampp\htdocs\e2\p4\console(12): E2\App->console(Array)
#4 {main}
  thrown in C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\Database.php on line 22

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1049] Unknown database 'my app' in C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\Database.php:22
Stack trace:
#0 C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\App.php(100): E2\Database->__construct('127.0.0.1', 'my app', 'root', NULL, 'utf8mb4')
#1 C:\xampp\htdocs\e2\p4\app\Commands\AppCommand.php(20): E2\App->db()
#2 C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\App.php(80): App\Commands\AppCommand->migrate()
#3 C:\xampp\htdocs\e2\p4\console(12): E2\App->console(Array)
#4 {main}
  thrown in C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\Database.php on line 22

warning: LF will be replaced by CRLF in app/Commands/AppCommand.php.
The file will have its original line endings in your working directory
```

In the video tutorial (week 14, part 4) the professor troubleshoots a similar error by updating the DB_name and app_name in .env which i have tried unsuccessfully.

**Comment by RGPhD** [comment]
Hi @janenycxo,

Did you update your database name to ```DB_NAME='p4'``` on production?  I am not certain but it looks like you might have your ```DB_NAME``` as ```'my app'```. 

Robelyn

**Comment by RGPhD** [comment]
Hello again Jane Yeh,
Did you ```CREATE DATABASE p4;``` in mysql mode on production in the mysql command line tool and then confirm your p4 database was created with ```SHOW DATABASES;``` ?
Robelyn

**Comment by susanBuck** [comment]
Confirming @RGPhD's suggestions.

**Comment by janenycxo** [comment]
thank you!
