### ISSUE TITLE
Can't display list of items in view

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#125]
My list of items in my table aren't showing in my ```list.blade.php``` file. It shows when I ```dump```, however, but when I try invoking it into my ```list.blade.php``` file, it doesn't show. I suspect it has something to do with my methods (```$apps``` vs ```$app```) in my ```AppController.php``` file but I'm not too sure since I think I'm using them correctly.

This is what I have in my ```list.blade.php``` file
```
@section('content')

List of Registrants Here
<ul>
    @foreach($apps as $app)

    <li>{{ $app['title'] }}</li>

    @endforeach
</ul>

@endsection
```

And this is what i have in my AppController.php file
```
 public function list()
    {
        $apps = ($this->app->db()->all('users'));
        return $this->app->view('list', ['apps' => $apps]);
    }

```

This is the error I'm getting:
```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function config() on array in /Applications/XAMPP/xamppfiles/htdocs/e2/p4/cache/4a2b7dc975559c9d3febfc8feca2f8d5dcc8b7a3.php:6 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/illuminate/view/Engines/PhpEngine.php(43): include() #1 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/Applications/X...', Array) #2 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/Applications/X...', Array) #3 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents() #4 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents() #5 /Applications/XAMPP/xamppfiles/htdocs/e2/p4/cache/a111441d37c9feeeb6a41d51e65b6826937f13ef.php(17): Illuminate\V in /Applications/XAMPP/xamppfiles/htdocs/e2/p4/cache/4a2b7dc975559c9d3febfc8feca2f8d5dcc8b7a3.php on line 6
```

**Comment by susanBuck** [comment]
Cloning your code now to look.

**Comment by susanBuck** [comment]
> I suspect it has something to do with my methods ($apps vs $app) in my AppController.php

You are correct. There's a naming conflict. The framework defines a variable `$app` to be used in your views.

With the following code, you are overwriting that:

```php
@foreach($apps as $app)
    <li>{{ $app['title'] }}</li>
@endforeach
```

To fix, use a different variable name such as `$thisApp`:
```php
<ul>
    @foreach($apps as $thisApp)
        <li>{{ $thisApp['title'] }}</li>
    @endforeach
</ul>
```

![image](https://user-images.githubusercontent.com/237711/71039591-81cb9a00-20f2-11ea-9fe5-669d227d7476.png)

**Comment by jeremiahazurin** [comment]
Thank you!
