### ISSUE TITLE
Digital Ocean Database Password Error 

### ISSUE THREAD

**Issue by MPVaccaro** [susanBuck/e2-fall19#89]
I set up the ```mysql>``` digital ocean database according to the video, and all seemed to go well - until I got to the ```migrate``` step.

It seems my password is not being taken.

This is my edited .env file:
```
APP_NAME='ZipFoods'
APP_URL='http://zipfoods.junkpileart.com'

DB_HOST='localhost'
DB_NAME='zipfoods'
DB_USERNAME='e2'
DB_USERNAME='school'
```
This is the error message that comes up in the command line when I tried to migrate:

```
mysql> quit;
Bye
root@e2:/var/www/html/e2/zipfoods# nano .env
root@e2:/var/www/html/e2/zipfoods# php console App migrate
^ "Executing App\Commands\AppCommand@migrate"
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'e2'@'localhost' (using password: NO) in /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php:22
Stack trace:
#0 /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(106): E2\Database->__construct('127.0.0.1', 'zipfoods', 'e2', NULL, 'utf8mb4')
#1 /var/www/html/e2/zipfoods/app/Commands/AppCommand.php(18): E2\App->db()
#2 /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(86): App\Commands\AppCommand->migrate()
#3 /var/www/html/e2/zipfoods/console(11): E2\App->console(Array)
#4 {main}
  thrown in /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php on line 22

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'e2'@'localhost' (using password: NO) in /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php:22
Stack trace:
#0 /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(106): E2\Database->__construct('127.0.0.1', 'zipfoods', 'e2', NULL, 'utf8mb4')
#1 /var/www/html/e2/zipfoods/app/Commands/AppCommand.php(18): E2\App->db()
#2 /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(86): App\Commands\AppCommand->migrate()
#3 /var/www/html/e2/zipfoods/console(11): E2\App->console(Array)
#4 {main}
  thrown in /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php on line 22
root@e2:/var/www/html/e2/zipfoods# 
```

I have run FLUSH PRIVILEGES, started, closed and restarted the terminal, but the result is the same.  I am afraid to fiddle with passwords for risk of making it worse.

**Comment by susanBuck** [comment]
Hi @MPVaccaro -

```
DB_USERNAME='e2'
DB_USERNAME='school'
```

Should be:
```
DB_USERNAME='e2'
DB_PASSWORD='school'
```

**Comment by MPVaccaro** [comment]
Thank you! That solved it.
