### ISSUE TITLE
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1044] Access denied

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#91]
I'm getting the errors on trying to get all the table data: 
```dump($this->app->db()->all('products'));```

> Notice: Undefined variable: usename in C:\xampp\htdocs\e2\zipfoods\vendor\susanbuck\e2core\src\App.php on line 66

> Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'zipfoods' in C:\xampp\htdocs\e2\zipfoods\vendor\susanbuck\e2core\src\Database.php:22 Stack trace: #0 C:\xampp\htdocs\e2\zipfoods\vendor\susanbuck\e2core\src\App.php(66): E2\Database->__construct('localhost', 'zipfoods', NULL, NULL, 'utf8mb4') #1 C:\xampp\htdocs\e2\zipfoods\app\Controllers\AppController.php(98): E2\App->db() #2 C:\xampp\htdocs\e2\zipfoods\vendor\susanbuck\e2core\src\App.php(106): App\Controllers\AppController->practice2() #3 C:\xampp\htdocs\e2\zipfoods\public\index.php(15): E2\App->route() #4 {main} thrown in C:\xampp\htdocs\e2\zipfoods\vendor\susanbuck\e2core\src\Database.php on line 22

In env.php
```php
APP_NAME='ZipFoods'
APP_URL='http://zipfoods.loc'

DB_HOST='localhost'
DB_NAME='zipfoods'
DB_USERNAME='root'
DB_PASSWORD=''

```

In AppController.php
```php
<?php
namespace App\Controllers;

class AppController extends Controller
{
    /**
     *
     */
    public function index()
    {
        $welcomes = ['Welcome', 'Aloha!', 'Welkom', 'Bienvenidos', 'Bienvenu', 'Welkomma'];
        
        return $this->app->view('index', [
            'welcome' => $welcomes[array_rand($welcomes)]
        ]);
    }

    public function contact()
    {
        return $this->app->view('contact');
    }

    public function about()
    {
        return $this->app->view('about');
    }

    public function practice()
    {
        # Set up all the variables we need to make a connection
        $host = $this->app->env('DB_HOST');
        $database = $this->app->env('DB_NAME');
        $username = $this->app->env('DB_USERNAME');
        $password = $this->app->env('DB_PASSWORD');
        $charset = $this->app->env('DB_CHARSET', 'utf8mb4');

        # DSN (Data Source Name) string
        # contains the information required to connect to the database
        $dsn = "mysql:host=$host;dbname=$database;charset=$charset";

        # Driver-specific connection options
        $options = [
        \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
        \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC,
        \PDO::ATTR_EMULATE_PREPARES => false,
    ];

        try {
            # Create a PDO instance representing a connection to a database
            $pdo = new \PDO($dsn, $username, $password, $options);
        } catch (\PDOException $e) {
            throw new \PDOException($e->getMessage(), (int)$e->getCode());
        }

        #EXAMPLE 1) Read Data
        # Write a SQL query
        $sql = "SELECT * FROM products WHERE name LIKE '%Strawberries%'";

        # Execute the statement, getting the result set as a PDOStatement object
        # https://www.php.net/manual/en/pdo.query.php
        $statement = $pdo->query($sql);

        # https://www.php.net/manual/en/pdostatement.fetchall.php
        dump($statement->fetchAll());

        #EXAMPLE 2) Create Data

        $sql = "INSERT INTO products (name, description, price, available, weight, perishable) 
        values (
            'Driscoll’s Strawberries', 
            'Driscoll’s Strawberries are consistently the best, sweetest, juiciest strawberries available. This size is the best selling, as it is both convenient for completing a cherished family recipes and for preparing a quick snack straight from the fridge.',
            4.99, 
            0, 
            1,
            1)";

        //$pdo->query($sql);

        #EXAMPLE 3)
        # Note that the six ?'s in this statement will correlate to the six values in our $data array
        $sqlTemplate = "INSERT INTO products (name, description, price, available, weight, perishable) values (?, ?, ?, ?, ?, ?)";

        $values = [
            'Driscoll’s Strawberries',
            'Driscoll’s Strawberries are consistently the best, sweetest, juiciest strawberries available. This size is the best selling, as it is both convenient for completing a cherished family recipes and for preparing a quick snack straight from the fridge.',
            4.99,
            0,
            1,
            1,
        ];

        # Prepare & Execute
        $statement = $pdo->prepare($sqlTemplate);
        $statement->execute($values);
    }
    public function practice2()
    {
        dump($this->app->db()->all('products'));
    }
}

```

**Comment by anyav77** [comment]
I found a typo in App.php

```$this->db = new Database($host, $database, $usename, $password, 'utf8mb4');```
fixed:
```$this->db = new Database($host, $database, $username, $password, 'utf8mb4');```
